name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    env:
      VERSION: v10.2.3
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          version: ${{ env.VERSION }}

      - name: Verify
        run: |
          set -x
          git ls-remote --tags origin "${VERSION}" | grep -q "refs/tags/${VERSION}"

      - name: Teardown
        if: ${{ always() }}
        run: |
          set -x
          git push origin "${VERSION}" --delete || true

  test-major:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    env:
      VERSION: v11.2.3
      MAJOR_VERSION: v11
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          version: ${{ env.VERSION }}
          major: true

      - name: Verify
        run: |
          set -x
          git ls-remote --tags origin "${VERSION}" | grep -q "refs/tags/${VERSION}"
          git ls-remote --tags origin "${MAJOR_VERSION}" | grep -q "refs/tags/${MAJOR_VERSION}"

      - name: Teardown
        if: ${{ always() }}
        run: |
          set -x
          git push origin "${VERSION}" --delete || true
          git push origin "${MAJOR_VERSION}" --delete || true
